Text_BootUpPC:
	.string "{PLAYER} stabbed the PC.$"

gText_WhichPCShouldBeAccessed::
	.string "Which PC do you want to be with ur skibidimon be accessed?$"

gText_AccessedSomeonesPC::
	.string "Accessed Skibidi's PC.$"

gText_StorageSystemOpened::
	.string "Pokémon Storage System opened.$"

gText_AccessedPlayersPC::
	.string "Accessed {PLAYER}'s PC.$"

gText_AccessedLanettesPC::
	.string "Accessed Sigma's PC.$"
